mainsite/mainsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^slauson/', include('slauson.urls', namespace='slauson')),
    url(r'^api/snippets/', include('snippets.api.urls', namespace='snippets-api')),
    # url(r'^api/users/', include('slauson.api.urls', namespace='users-api')),
    url(r'^api/slauson/', include('slauson.api.urls', namespace='slauson-api'))
]

mainsite/slauson/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.BasePageView.as_view(), name='basepage'),
    url(r'^home/$', views.HomePageView.as_view(), name='homepage'),
    url(r'^accounts/register/$', views.RegisterPageView.as_view(), name='register'),
    url(r'^accounts/login/$', views.LoginView.as_view(), name='login'),
    url(r'^accounts/logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^accounts/profile/$', views.ProfileUpdateView.as_view(), name='profile'),
    url(r'^accounts/detail/(?P<slug>[\w.@+-]+)/$', views.ProfileDetailView.as_view(), name='detail'),
    url(r'^accounts/list/$', views.ProfilesListView.as_view(), name='list'),

    url(r'^accounts/password_reset/$', auth_views.password_reset, {'template_name': 'accounts/password_reset_form.html'}
        , name='password_reset',),

    url(r'^accounts/password_reset/done/$', auth_views.password_reset_done, {'template_name':
        'accounts/password_reset_done.html'}, name='password_reset_done'),

    url(r'^accounts/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, {'template_name': 'accounts/password_reset_confirm.html'},
        name='password_reset_confirm'),

    url(r'^accounts/reset/done/$', auth_views.password_reset_complete, {'template_name':
        'accounts/password_reset_done.html'}, name='password_reset_complete'),

]

mainsite/slauson/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.template.defaultfilters import slugify
from django.core.urlresolvers import reverse
from django.db.models.signals import post_save
# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.CharField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return "%s' profile" % self.user

    '''def save(self, *args, **kwargs):
        self.slug = (slugify(self.location))
        super(Profile, self).save(*args, **kwargs)'''

    def get_absolute_url(self):
        return reverse('detail', kwargs={'slug': self.slug})


def create_profile(sender, **kwargs):
    user = kwargs["instance"]
    if kwargs["created"]:
        profile = Profile(user=user)
        profile.save()


post_save.connect(create_profile, sender=User)

mainsite/templates/accounts/change_password.html
{% extends 'base.html' %}
{% block title %} Change Password {% endblock title %}
{% load crispy_forms_tags %}



{% block content %}
<br>
<div class="container">
    <div class="ui segment five wide column">
        <form class="ui form" method="post" action="">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit">
        </form>

    </div>
</div>

{% endblock %}

mainsite/templates/accounts/detail.html
{% extends 'base.html' %}
{% block title %} {{user.get_full_name}} {% endblock title %}



{% block content %}
<div class="container">

<div class="col-md-5">
    <p>{{user.profile.bio}}</p>
    <p>{{user.profile.location}}</p>
    <p>{{user.get_full_name}}</p>
    <p>{{user.profile.birth_date|date:"j F , Y" }}</p>
</div>


</div>
{% endblock %}

mainsite/templates/accounts/list.html
{% extends 'base.html' %}
{% block title %} List {% endblock title %}



{% block content %}
<div class="ui container">

<div class="five column wide">

    <table class="ui celled table" id="profile-table">
        <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Bio</th>
            <th>Location</th>
            <th>Date of birth</th>
        </tr>
        </thead>
        <tbody>
            {% for profile in profile_list %}
        <tr>
            <td>{{profile.id}}</td>
            <td>{{profile.user.get_full_name}}</td>
            <td>{{profile.bio}}</td>
            <td>{{profile.location}}</td>
            <td>{{profile.birth_date|date:"j F , Y" }}</td>
            <td></td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="7" class="text-center bg-warning"> No Profile</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>


</div>
{% endblock %}

mainsite/templates/accounts/login.html
{% extends 'base.html' %}
{% block title %} Login {% endblock title %}


{% block content %}
<br>
<div class="container">
    <div class="ui segment five wide column">
        <form class="ui form" method="post" action="">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit">
        </form>

    </div>
</div>

{% endblock %}

mainsite/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
  <p>
    Your password has been set. You may go ahead and <a href="{% url 'signin' %}">sign in</a> now.
  </p>
{% endblock %}

mainsite/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
  {% if validlink %}
    <h3>Change password</h3>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Change password</button>
    </form>
  {% else %}
    <p>
      The password reset link was invalid, possibly because it has already been used.
      Please request a new password reset.
    </p>
  {% endif %}
{% endblock %}

mainsite/templates/accounts/password_reset_done.html
{% extends 'base.html' %}

{% block content %}
  <p>
    We've emailed you instructions for setting your password, if an account exists with the email you entered.
    You should receive them shortly.
  </p>
  <p>
    If you don't receive an email, please make sure you've entered the address you registered with,
    and check your spam folder.
  </p>
{% endblock %}

mainsite/templates/accounts/password_reset_email.html
{% autoescape off %}

To initiate the password reset process for your {{ user.get_username }} TestSite Account,
click the link below:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
Slauson Tech Inc.

{% endautoescape %}

mainsite/templates/accounts/password_reset_form.html
{% extends 'base.html' %}
{% block title %} Reset Password {% endblock title %}

{% block content %}
  <h3>Forgot password</h3>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>

{% endblock %}

mainsite/templates/accounts/profile.html
{% extends 'base.html' %}
{% block title %} Page {% endblock title %}
{% load i18n %}
{% load crispy_forms_tags %}


{% block content %}
<div class='row'>
<div class='col-sm-6 col-sm-offset-3'>
<h1>Register for free!</h1>

  <form method="post" action=".">
  {% csrf_token %}

  {{ form|crispy }}

  <input class='btn btn-block btn-primary' type="submit" value="{% trans 'Join' %}" />
</form>
</div>
</div>

{% endblock %}

mainsite/templates/accounts/signup.html
{% extends 'base.html' %}
{% block title %} Sign Up {% endblock title %}
{% load crispy_forms_tags %}



{% block content %}
<br>
<div class="container">
    <div class="ui segment five wide column">
        <form class="ui form" method="post" action="">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit">
        </form>

    </div>
</div>

{% endblock %}